local_backend: true

backend:
  name: git-gateway # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: master # Branch to update
  repo: mkimbo/hyblog-final # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: 'Blog'
    folder: 'content'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}.md'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: info
    label: 'Information'
    files:
      - label: 'About Hyblog'
        name: 'about_hyblog'
        file: 'site/information/about-hyblog.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Details', name: 'details', widget: 'text' }
      - label: 'About Hyreads'
        name: 'about_hyreads'
        file: 'site/information/about-hyreads.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Details', name: 'details', widget: 'text' }
          - label: 'Features'
            name: 'features'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Details', name: 'details', widget: 'text' }
      - label: 'Frequently Asked Questions'
        name: 'faqs'
        file: 'site/information/faqs.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Questions'
            name: 'questions'
            widget: 'list'
            fields:
              - { label: 'Question', name: 'question', widget: 'string' }
              - { label: 'Answer', name: 'answer', widget: 'text' }
